### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by lenacoll** [bioDS/treeOclock#2]
@Lars-B Can you give me the trees for which the memory leak occurs?

**Comment by Lars-B** [comment]
I have fixed the memory leak issue.
When `Tree_List return_findpath` is called the returned Tree_List needs to be freed after usage, in the DTT package branch I added a free_tree_list function for this, which we might want to add to Master, maybe also a reminder for the user to free the memory of the returned tree_list.
Same would be the case for `Path findpath`.

**Comment by gavryushkin** [comment]
This leak looks fixed? Please reopen otherwise.

**Comment by lenacoll** [comment]
The current solution is not very neat -- we need to free the Tree_Array from C in the python code.
I suggest we add a conversion of our tree structure to a python tree structure to avoid having this problem, if we at some point plan to publish this repo/parts of this repo as python package.
