### ISSUE TITLE
139 on newick strings

### ISSUE THREAD

**Issue by gavryushkin** [bioDS/treeOclock#4]
Error message `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` after running it directly in python after building with make. Worked fine on the example input files from the repo.

```
from tree_io import read_newick
from tree_structs import findpath_distance
​
newick_str = "(((7:0.06868257819,(20:0.02964868806,21:0.02964868806):0.03903389013):0.1042569489,(((((29:0.01270612141,30:0.01270612141):0.01771552468,19:0.0304216461):0.02550493264,11:0.05592657874):0.06617456767,((12:0.05472055727,13:0.05472055727):0.02421792724,(9:0.05724582078,10:0.05724582078):0.02169266373):0.0431626619):0.04780352892,(((24:0.02550858298,(27:0.02441077399,28:0.02441077399):0.001097808993):0.04980295134,4:0.07531153432):0.09038758802,2:0.1656991223):0.004205552989):0.003034851755):0.003578587408,((((((25:0.02482626361,26:0.02482626361):0.02554515754,((15:0.03685974834,16:0.03685974834):0.009891218212,14:0.04675096655):0.0036204546):0.06595014748,(5:0.07084572098,6:0.07084572098):0.04547584766):0.01201396307,(22:0.02694130675,23:0.02694130675):0.101394225):0.03309748355,(3:0.08619590656,((17:0.03682821325,18:0.03682821325):0.02661757797,8:0.06344579122):0.02275011533):0.07523710869):0.012108986,1:0.1735420013):0.002976113241):0;"
​
newick_tree = read_newick(newick_str)
newick_tree2 = read_newick(newick_str)
​
print(newick_str)
​
d = findpath_distance(newick_tree, newick_tree2)
print(d)

**Comment by Lars-B** [comment]
The `ete3` newick parser does not appear to have an issue with this, maybe we want to switch to that parser instead @lenacoll ? See [the package](https://github.com/bioDS/treeOclock/tree/DTT-Package/treeoclock/trees) (_converter and time_trees)where this is already implemented so maybe its just copy and paste.

**Comment by lenacoll** [comment]
I updated dct_parser, which fixed the problem (it has already been addressed in that repo). See commit 1b2aa0218ec3a6aee906b64a2dbd6945234e6957.
@Lars-B Since we do not use exactly the same tree data structure as ete3, I'm not sure if it's necessary to use that package, it feels more like an unnecessary extra step to me.
